version: "2"

services:
  # julu weilu wx server
  julu_weilu_wx:
    image: ccr.ccs.tencentyun.com/julu/weilu_wx
    expose:
      - 51001
    environment:
      MYSQL_URL: "mariadb:3306"
      WX_MYSQL_USER: "wx"
      WX_MYSQL_PASSWORD: ${WX_MYSQL_PASSWORD}
      WX_DATABASE: "wx"
    networks:
      - internal
    restart: on-failure
networks:
  internal:
    external: true
