# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
      - image: mariadb
        environment:
          MYSQL_ROOT_PASSWORD: "123123"
          MYSQL_ROOT_HOST: "%"
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    working_directory: /go/src/github.com/stevenkitter/weilu
    parallelism: 1
    environment:
      WX_SERVER_ADDRESS: "localhost:51001"
      WX_MYSQL_PASSWORD: rWk1hvqMT62K2JYH
      MYSQL_URL: "localhost:3306"
      WX_MYSQL_USER: "wx"
      WX_DATABASE: "wx"
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: sudo apt-get update && sudo apt install -y mysql-client
      - run:
          name: init mysql
          command: |
            sh ./script_mysql_init/init.sh
      - run:
          name: build services wx to app
          command: |
            cd services/wx
            CGO_ENABLED=0 GOOS=linux go build -o app .

      - run:
          name: run the micro services
          command: |
            cd services/wx
            ./app &
            ps -aux
            lsof -i :51001
      - run: go test -v ./...

      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: push services wx to tencent image
          command: |
            cd services/wx
            docker build -t ccr.ccs.tencentyun.com/julu/weilu_wx .
            docker login -u 100000776220 -p wangxu226 ccr.ccs.tencentyun.com
            docker push ccr.ccs.tencentyun.com/julu/weilu_wx
  deploy:
    machine:
      enable: true
    working_directory: ~/julu
    environment:
      JULU_PATH: "/home/ubuntu/production/julu"
    steps:
      - checkout
      - run:
          name: Deploy over ssh
          command: |
            ls
            scp docker-compose.yml $SSH_USER@$SSH_HOST:$JULU_PATH
            scp deploy.sh $SSH_USER@$SSH_HOST:$JULU_PATH
            ssh $SSH_USER@$SSH_HOST "cd $JULU_PATH && sh deploy.sh"
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
