version: "2"

services:
  #mariadb
  image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
    expose:
      - 3306
    networks:
      - internal
  # julu weilu wx server
  julu_weilu_wx:
    image: ccr.ccs.tencentyun.com/julu/weilu_wx
    expose:
      - 51001
    environment:
      MYSQL_URL: mariadb:3306
    networks:
      - internal
    depends_on:
      - mariadb
networks:
  internal:
    external: true
